#!/bin/bash

if [ -z "$1" ]; then
	echo "ERROR: please supply a path to the cached-completion init script" 1>&2
else
	[ -n "$2" ] && bash_cached_completions_dir="$2"
	_bash_cached_completions_script="$1"
	function _bash_cached_completions {
		COMPREPLY=()
		words=$(${_bash_cached_completions_script} "$COMP_CWORD" "${COMP_WORDS[@]}" 2>/tmp/cache_completions.log)
		COMPREPLY=( $(compgen -W "${words}" -- ${COMP_WORDS[COMP_CWORD]}) )
		return 0
	}

	[ -n "$bash_cached_completions_dir" ] || bash_cached_completions_dir=~/.config/bashcomplete
	function _bash_cached_completions_init {
		for f in $bash_cached_completions_dir/*.py; do
			local filename command
			filename=${f##*/}
			command=${filename/%.py/}
			complete -f -F _bash_cached_completions $command
		done
	}

	_bash_cached_completions_init
fi
