#!/bin/bash

if [ -z "$1" ]; then
	echo "ERROR: please supply a path to the cached-completion init script" 1>&2
else
	[ -n "$2" ] && bashcomplete_config_dir="$2"
	_bashcomplete_cached_script="$1"
	function _bashcomplete_cached {
		COMPREPLY=()
		words=$(${_bashcomplete_cached_script} "$COMP_CWORD" "${COMP_WORDS[@]}" 2>/tmp/bashcomplete.log)
		COMPREPLY=( $(compgen -W "${words}" -- ${COMP_WORDS[COMP_CWORD]}) )
		return 0
	}

	[ -n "$bashcomplete_config_dir" ] || bashcomplete_config_dir=~/.config/bashcomplete
	export bashcomplete_config_dir
	function _bashcomplete_cached_init {
		for f in $bashcomplete_config_dir/*.py; do
			local filename command
			filename=${f##*/}
			command=${filename/%.py/}
			complete -f -F _bashcomplete_cached $command
		done
	}

	_bashcomplete_cached_init
fi
